Bwockner/sortable chunked array
Euclideon/udcore pull request #127
Opened 2022-04-19 00:36 UTC by bwockner

Added support for LegacyRandomAccessIterator to udChunkedArray

2022-04-19 07:52 UTC, samsinsane requested changes

2022-04-19 07:52 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +  ++it;
You're not validating that the return value is a valid iterator.

2022-04-19 07:52 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +  EXPECT_EQ(it == it, true);
These tests aren't really that valuable. You should create a second iterator to compare with at the very least.

2022-04-19 07:52 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +  it = it + 8;
This seems entirely arbitrary?

2022-04-19 07:52 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +  EXPECT_EQ(it < it + 3, true);
Brackets.

2022-04-19 07:52 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +  EXPECT_EQ(it2 > it, false);
How does this differ to the above `- 1` variants?

2022-04-19 07:52 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +  EXPECT_EQ(it2, --it);
How does this differ to the `--it` test above?

2022-04-19 07:52 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +  EXPECT_EQ(it, it2);
What is this testing that the above hasn't already?

2022-04-19 07:52 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +  EXPECT_EQ(i, array.length + 1);
What is this testing?

2022-04-19 07:52 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +  }
What is this testing?

2022-04-19 07:52 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +  for (int i = 0; i < 500; ++i) // ensure that the array is forced to grow
This comment doesn't make sense. Are you adding 500 items to add another chunk, or to trigger the reallocation of the chunks array? Also, why?

2022-04-19 07:52 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +    array.PushBack(i % 4);
Why `i%4`?

2022-04-19 07:52 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +  //non zero inset:
`:`?

2022-04-19 07:52 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +    EXPECT_EQ(previous > el, false);
```suggestion
    EXPECT_TRUE(previous <= el);
```

Testing the positive case makes more sense for something like this.

2022-04-19 07:52 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +  //testing std::reverse_iterator: should return reverse order
What's this needed for? You've already tested `std::sort` above.

2022-04-19 07:52 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +    EXPECT_EQ(*iter > previous, false);
Same as above, test the positive case.

2022-04-19 23:28 UTC, bwockner commented on Source/udThread.cpp
> +    pThread->refCount = 2;
accidental inclusion

2022-04-19 23:29 UTC, bwockner commented on udTest/src/udChunkedArrayTests.cpp
> +    array.PushBack(i % 4);
Just constructs an out of order array - open to suggestions on a better way of doing this deterministically

2022-04-19 23:32 UTC, bwockner commented on udTest/src/udChunkedArrayTests.cpp
> +  //testing std::reverse_iterator: should return reverse order
Testing compatibility with std::reverse_iterator to ensure it doesn't use the interface in a way that isn't tested by sort

2022-04-19 23:38 UTC, bwockner commented on Include/udChunkedArray.h
> +  //return udChunkedArray<T>::iterator{ &ppChunks[0], 0, chunkElementCount };
The constructor was added when I was adding variables to the internal state of the iterator during testing which required rearrangement of the intialiser list. I do prefer this since it isn't completely clear what variables are being set by the initialiser list just by looking at the class definition due to the large number of method declarations in the class.

2022-04-19 23:49 UTC, bwockner commented on udTest/src/udChunkedArrayTests.cpp
> +  it = it + 8;
Intent was to have the iterator cross a chunk boundary - I will add a comment to that effect

2022-04-20 04:25 UTC, bwockner commented on udTest/src/udChunkedArrayTests.cpp
> +  ++it;
Do you mean checking that 
it.ppCurrentChunk < array.ppChunks 
and that 
it.currChunkIndex >= (it.ppCurrentChunk == array.ppChunks ? array.inset : 0) 

or something different?

2022-04-21 01:40 UTC, samsinsane commented on udTest/src/udChunkedArrayTests.cpp
> +  ++it;
I meant:
```c++
auto it2 = ++it;
EXPECT_EQ(it, it2);
```

2022-04-22 00:45 UTC, samsinsane approved these changes

2022-04-22 00:47 UTC, merged