Minimal implementation to spill ChunkedArray chunks to a temp file
Euclideon/udcore pull request #149
Opened 2022-11-10 00:48 UTC by dpev

2022-11-10 23:29 UTC, OsiJr requested changes

2022-11-10 23:29 UTC, OsiJr commented on udTest/src/udChunkedArrayTests.cpp
> +  // udVirtualChunkedArray is in udOBJ for the moment, and may move to udCore in the future
This is no longer true :)

2022-11-10 23:29 UTC, OsiJr commented on Include/udVirtualChunkedArray.h
> +  bool IsChunkLoaded(size_t index) const { return (index < array.length &&array.ppChunks[(index + array.inset) >> array.chunkElementCountShift] != nullptr); } // For unit testing
Name isn't terrible but something like `IsElementInMemory` might be a tiny bit clearer that index is the element rather than the chunk

2022-11-10 23:29 UTC, OsiJr commented on Include/udVirtualChunkedArray.h
> +  udResult Init(size_t chunkElementCount, uint32_t maxChunksInMem = 0, udFile *pTempFile = nullptr);
This seems a bit risky. The caller has to create a file and then hold onto the handle for the lifetime of the virtual chunked array. It seems that it would be better if a filename/handle was required here instead and the virtual chunked array handled the lifetime of the object.

Failing that this class should probably handle if the caller closes the function or some other silly thing.

2022-11-10 23:40 UTC, dpev commented on Include/udVirtualChunkedArray.h
> +  udResult Init(size_t chunkElementCount, uint32_t maxChunksInMem = 0, udFile *pTempFile = nullptr);
Indeed that's how it was when I started, however the use-case has lots of different chunked arrays (positions, uv's etc) some of which weren't present so I was ending up with lots of files, some epmty, and having to create lots of unique names, so having one shared was more convenient for the use-case.

2022-11-14 02:57 UTC, dpev commented on Include/udVirtualChunkedArray.h
> +  udResult Init(size_t chunkElementCount, uint32_t maxChunksInMem = 0, udFile *pTempFile = nullptr);
That's done now

2022-11-30 00:39 UTC, OsiJr approved these changes

2022-11-30 00:45 UTC, merged