Added function to set a string more conveniently
Euclideon/udcore pull request #154
Opened 2022-12-07 05:36 UTC by dpev

This solves the issue of not being able to set strings that have quote characters with the normal Set() method.
Also reordered a couple of Set variants to match order in implementation

2022-12-07 05:39 UTC, OsiJr approved these changes

2022-12-07 05:40 UTC, samsinsane requested changes

2022-12-07 05:40 UTC, samsinsane commented on udTest/src/udJSONTests.cpp
> +  EXPECT_EQ(udR_Success, v.SetMemberString("one", "array[]"));
This seems like a bad change? I think the code was testing that `Set` with a `udJSON*` worked on an array value too, rather than it working with a string.

Additionally, are there any tests remaining for the `Set(udJSON  *pJSON, ...)` function?

2022-12-07 05:59 UTC, dpev commented on udTest/src/udJSONTests.cpp
> +  EXPECT_EQ(udR_Success, v.SetMemberString("one", "array[]"));
Oh yeah that's a really good spot. I should put that one back.

2022-12-07 06:05 UTC, samsinsane submitted a review, later dismissed

2022-12-14 02:03 UTC, OsiJr approved these changes

2022-12-14 02:03 UTC, merged