C-compile compatibility for udMath.h, udPlatform.h and udResult.h
Euclideon/udcore pull request #164
Opened 2023-05-03 05:06 UTC by dpev

Paves the way for removal of udGeometryMath etc

2023-05-15 06:24 UTC, samsinsane requested changes

2023-05-15 06:24 UTC, samsinsane commented on Source/udJSON.cpp
> +//udResult udJSON::Set(const udDouble4x4 &v, bool shrink)
Delete perhaps?

2023-05-15 06:24 UTC, samsinsane commented on Source/udPlatform.cpp
Also doesn't need to change.

2023-05-15 06:24 UTC, samsinsane commented on Source/udResult.cpp
Also doesn't need to change.

2023-05-15 06:24 UTC, samsinsane commented on Source/udSocket.cpp
> +#define NOMINMAX // Required on Windows in order to use std::min/std::max from <algorithm>
Not required if put into `udPlatform.h`

2023-05-15 06:24 UTC, samsinsane commented on Source/udStringUtil.cpp
> +#define NOMINMAX // Required on Windows in order to use std::min/std::max from <algorithm>
Same as above.

2023-05-15 06:24 UTC, samsinsane commented on Source/udUUID.cpp
> +#define NOMINMAX
Same as above.

2023-05-15 06:24 UTC, samsinsane commented on Source/udWorkerPool.cpp
> +#define NOMINMAX
Same as above.

2023-05-15 06:24 UTC, samsinsane commented on udTest/src/udCompressionTests.cpp
> +    EXPECT_NE(0, memcmp(input, pDeflated, min(UDARRAYSIZE(input), deflatedSize)));
If `NOMINMAX` is put into `udPlatform.h` the usages in this file will need to be updated to `std::`

2023-05-16 04:16 UTC, closed without merging

2023-05-16 04:18 UTC, dpev commented
Closing in favour of staging commits differently