Split udImageStreaming_SaveAs into two parts
Euclideon/udcore pull request #178
Opened 2023-08-01 06:27 UTC by dpev

Also includes the update for webtest.py to use Services

2023-08-01 07:21 UTC, samsinsane requested changes

2023-08-01 07:21 UTC, samsinsane commented on Include/udImage.h
> +udResult udImageStreaming_GetImage24(uint8_t **ppRBG, udImageStreaming *pImage, udImageSampleFlags flags = udISF_TopLeft, uint32_t *pWidth = nullptr, uint32_t *pHeight = nullptr);
Probably should some unit tests for this?

2023-08-01 07:38 UTC, dpev commented on Include/udImage.h
> +udResult udImageStreaming_GetImage24(uint8_t **ppRBG, udImageStreaming *pImage, udImageSampleFlags flags = udISF_TopLeft, uint32_t *pWidth = nullptr, uint32_t *pHeight = nullptr);
Indeed, will do

2023-08-02 04:05 UTC, samsinsane approved these changes

2023-08-02 04:42 UTC, merged